### ISSUE TITLE
Is there a way to inherit from generic-service or some other template?

### ISSUE THREAD

**Issue by rayterrill** [terraform-providers/terraform-provider-icinga2#24]

**Comment by rayterrill** [comment]
@lrsmith Are you looking for help maintaining? I might be able to help knock out some issues and catch up the provider to the functionality in the api.

**Comment by lrsmith** [comment]
@rayterrill I will never turn down any help. :)

**Comment by lazzurs** [comment]
@rayterrill this issue has been open for a while. Still relevant?

**Comment by rayterrill** [comment]
I'll close. We moved away from this project for maintaining Icinga because it seemed abandoned.
