### ISSUE TITLE
Incompatible with terraform 0.12

### ISSUE THREAD

**Issue by wegerhoff** [terraform-providers/terraform-provider-icinga2#31]
### Terraform Version
0.12.1

### Affected Resource(s)
provider icinga2

### Terraform Configuration Files
```hcl
provider "icinga2" {
  api_url                  = "https://<foobar>:5665/v1"
  api_user                 = "<username>"
  api_password             = "<password>"

  version = "0.2.0"
}
```

### Debug Output

`Error: failed to load provider "icinga2": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
`

### Expected Behavior

"terraform apply" and "terraform 0.12upgrade" succeed

### Actual Behavior

"terraform apply" and "terraform 0.12upgrade" fail when using terraform 0.12.1

### Steps to Reproduce

1.  Install terraform 0.12.1
2.  `terraform init`
3.  `terraform apply`

### References
https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html

**Comment by lazzurs** [comment]
Added pull request #32 which should fix this.

**Comment by lazzurs** [comment]
This issue should be closed.
