### ISSUE TITLE
Release 0.1.1

### ISSUE THREAD

**Issue by wndhydrnt** [terraform-providers/terraform-provider-icinga2#4]
We would like to use #3 in production. With Terraform 0.10.0 now being available, there is nothing that blocks us from doing so except a new release of this provider. Are there any plans to release 0.1.1 soon? Thanks!

**Comment by grubernaut** [comment]
Hey @wndhydrnt, thanks for the issue!
I just released v0.1.1 of the icinga2 provider, please let me know if this works for you. 
https://releases.hashicorp.com/terraform-provider-icinga2/0.1.1/
Thanks!
